---
- hosts: windows-rdsh

  vars_files:
    - vars/deviceTRUST.yml

  tasks:

    - name: Create Temp Folder
      win_file:
        path: '{{ devicetrust_exctract_dir }}'
        state: directory

    - name: Copy deviceTRUST Host
      win_copy:
        src: '../deviceTRUST/{{ devicetrust_host_install_file }}'
        dest: '{{ devicetrust_exctract_dir }}\'

    - name: Install deviceTRUST Host
      win_package:
        path: '{{ devicetrust_exctract_dir }}\{{ devicetrust_host_install_file }}'
        product_id: '{{ devicetrust_host_product_id }}'
        #creates_path: C:\Program Files\deviceTRUST\Host\Bin
        state: present
      register: deviceTRUST_Host_install

    - name: reboot if deviceTRUST Host requires it
      win_reboot:
      when: deviceTRUST_Host_install.reboot_required
