---
- hosts: windows-dc

  vars_files:
    - vars/generic.yml
    - vars/deviceTRUST.yml

  tasks:
    - name: Create Temp Folder
      win_file:
        path: '{{ devicetrust_exctract_dir }}'
        state: directory

    - name: Copy deviceTRUST Console
      win_copy:
        src: '../deviceTRUST/{{ devicetrust_console_install_file }}'
        dest: '{{ devicetrust_exctract_dir }}\'

    - name: Install deviceTRUST Console
      win_package:
        path: '{{ devicetrust_exctract_dir }}\{{ devicetrust_console_install_file }}'
        product_id: '{{ devicetrust_console_product_id }}'
        #creates_path: C:\Program Files\deviceTRUST\Console\Bin
        state: present
      register: deviceTRUST_Console_install

    - name: reboot if deviceTRUST Console requires it
      win_reboot:
      when: deviceTRUST_Console_install.reboot_required
