---
- hosts: windows-members

  vars_files:
    - vars/generic.yml


  roles:
    # - { role: ansible-role-win-disable-firewall }
    - { role: ansible-role-win-disable-nic-register-dns }
    - { role: ansible-role-win-domain-member }
