---
- hosts: windows-rdsh

  vars_files:
    - vars/generic.yml

  roles:
    - { role: ansible-role-win-rdsh }

  tasks:

    - name: install Chocolatey            # https://github.com/ansible/ansible/issues/53860
      win_chocolatey:
        name: chocolatey
        state: latest

    - name: disable enhanced exit codes   # https://github.com/ansible/ansible/issues/53860
      win_chocolatey_feature:
        name: useEnhancedExitCodes
        state: disabled

    - name: Install packages with chocolatey
      win_chocolatey:
        name: '{{ item }}'
        state: present
      with_items:
        - 7zip.install
        - firefox
        - notepadplusplus.install

