---
- import_playbook: generic-dc.yml
- import_playbook: generic-domain-members.yml
- import_playbook: generic-rdsh.yml

- import_playbook: deviceTRUST-dc.yml
- import_playbook: deviceTRUST-rdsh.yml
- import_playbook: deviceTRUST-client.yml
